title:        Chris Meyns
subtitle:		  early modern・plasticity・anonymity
description:  Researcher, philosophy geek. Into early modern, tech, typography, open science.
image:			  https://github.com/csmeyns/meyns/raw/gh-pages/img/portrait.jpg
url:			    http://csmeyns.github.io

name: 	Chris Meyns
email: 	c.s.meyns@gmail.com

markdown:    foghorn

# Analytics and webmaster tools stuff goes here
google_analytics: 	UA-54457536-1
google_verify: 		UA-54457536-1

# CV location (I envisage a PDF file here)
# cv:			http://bit.ly/UDmT6U

# Social media / online presence
twitter:	csmeyns
skype: 		csmeyns
